//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Pasword { get; set; }
        public Nullable<int> Account_Number { get; set; }
        public Nullable<int> credit { get; set; }
        public Nullable<int> BrunchCode { get; set; }
        public byte[] Image { get; set; }
        public string UserType { get; set; }
    
        public virtual Bank_branch1 Bank_branch1 { get; set; }
    }
}
